// Generated by Wrangler by running `wrangler types`

interface Env {
	FPC_CACHE: KVNamespace;
	PURGE_SECRET: string;
	DEBUG: string;
	DEFAULT_TTL: string;
	GRACE_SECONDS: string;
	HIT_FOR_PASS_SECONDS: string;
	RESPECT_PRIVATE_NO_CACHE: string;
	RESPECT_CACHE_CONTROL: string;
	CACHE_LOGGED_IN: string;
	GRAPHQL_PATH: string;
	STATIC_PATH_PATTERN: string;
	HEALTH_CHECK_PATTERN: string;
	MARKETING_PARAMS: string;
	EXCLUDED_PATHS: string;
	VARY_COOKIES: string;
	ALLOWED_COOKIE_NAMES: string;
	INCLUDED_RESPONSE_TYPES: string;
}
